### ISSUE TITLE
Consitional check failed

### ISSUE THREAD

**Issue by apitanga** [FlatKey/ansible-firewalld-role#2]
I'm getting this conditional check error since recently:

`The conditional check 'firewalld_purge_services and item not in firewalld_service_rules' failed. The error was: error while evaluating conditional (firewalld_purge_services and item not in firewalld_service_rules): 'firewalld_purge_services' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_10__soe/roles/FlatKey.firewalld/tasks/main.yml': line 53, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: purge unconfigured firewalld service rules\n  ^ here\n`

I don't have the firewalld_purge_services variable defined, but thought it was optional

**Comment by FlatKey** [comment]
You're right, it's ment to be an optional variable, but I forgot to define the default. I've fixed this issue with the explicit default value (false) in the release with the tag v1.2.3. Thank you very much for your report!
