### ISSUE TITLE
hardcoded interface enp4s0

### ISSUE THREAD

**Issue by richlv** [FlatKey/ansible-firewalld-role#3]
There seems to be a hardcoded interface name in https://github.com/FlatKey/ansible-firewalld-role/blob/master/tasks/main.yml#L25 :

    if [[ "$(/bin/firewall-cmd --get-zone-of-interface=enp4s0)" != "public" ]]

**Comment by FlatKey** [comment]
Thank you for your report, I'll add the possibility to configure the interface name.

**Comment by FlatKey** [comment]
Variable for configuration already exists, but the test of the system configuration contained hardcoded interface name and zone. Issue is fixed now.
